### ISSUE TITLE
Compiling errors with XCode 13 

### ISSUE THREAD

**Issue by ElihuJ** [IFTTT/ConnectSDK-iOS#292]
After upgrading XCode to version 13
The SDK is throwing compiler errors:
```Enum cases with associated values cannot be marked potentially unavailable with '@available```
![Screen Shot 2021-09-23 at 10 45 43 am](https://user-images.githubusercontent.com/30395400/134440050-001d0023-315e-4c22-939c-a29a8a252cbe.png)

**Comment by Daivest** [comment]
this one can be fixed by set 13.0 as deployment target
https://stackoverflow.com/questions/37160688/set-deployment-target-for-cocoapodss-pod

but the second is not so easy to fix =(
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/21379719/134525250-cbc6fa3f-3ad0-4f09-8436-d45638c0f90b.png">

**Comment by ssathy2** [comment]
Hi all, this issue has been fixed in the latest release 2.7.0. Please try it with that version. Thanks!

**Comment by meetmandar** [comment]
Looks good with Xcode 13

**Comment by ElihuJ** [comment]
Back working, thanks @ssathy2
